import os
import argparse
import pandas as pd
import matplotlib.pyplot as plt

def plot_psnr(df, save_dir):
    plt.figure(figsize=(12, 6))
    plt.plot(df["Method"], df["PSNR (dB)"].astype(float), marker='o', linewidth=3)
    plt.xticks(rotation=45, ha='right')
    plt.title("PSNR Comparison Across Methods", fontsize=16, fontweight='bold')
    plt.xlabel("Method")
    plt.ylabel("PSNR (dB)")
    plt.grid(True, alpha=0.3)
    plt.tight_layout()

    save_path = os.path.join(save_dir, "psnr_plot.png")
    plt.savefig(save_path, dpi=200, bbox_inches='tight')
    plt.close()
    print(f"✅ Saved PSNR graph → {save_path}")


def plot_ssim(df, save_dir):
    plt.figure(figsize=(12, 6))
    plt.plot(df["Method"], df["SSIM"].astype(float), marker='o', linewidth=3)
    plt.xticks(rotation=45, ha='right')
    plt.title("SSIM Comparison Across Methods", fontsize=16, fontweight='bold')
    plt.xlabel("Method")
    plt.ylabel("SSIM")
    plt.ylim([0, 1])
    plt.grid(True, alpha=0.3)
    plt.tight_layout()

    save_path = os.path.join(save_dir, "ssim_plot.png")
    plt.savefig(save_path, dpi=200, bbox_inches='tight')
    plt.close()
    print(f"✅ Saved SSIM graph → {save_path}")


def plot_psnr_bar(df, save_dir):
    plt.figure(figsize=(12, 6))
    values = df["PSNR (dB)"].astype(float)

    plt.bar(df["Method"], values, edgecolor='black')
    plt.xticks(rotation=45, ha='right')
    plt.title("PSNR Bar Chart", fontsize=16, fontweight='bold')
    plt.ylabel("PSNR (dB)")
    plt.grid(axis='y', alpha=0.3)
    plt.tight_layout()

    save_path = os.path.join(save_dir, "psnr_bar_chart.png")
    plt.savefig(save_path, dpi=200, bbox_inches='tight')
    plt.close()
    print(f"✅ Saved PSNR Bar Chart → {save_path}")


def plot_ssim_bar(df, save_dir):
    plt.figure(figsize=(12, 6))
    values = df["SSIM"].astype(float)

    plt.bar(df["Method"], values, edgecolor='black')
    plt.xticks(rotation=45, ha='right')
    plt.title("SSIM Bar Chart", fontsize=16, fontweight='bold')
    plt.ylabel("SSIM")
    plt.ylim([0, 1])
    plt.grid(axis='y', alpha=0.3)
    plt.tight_layout()

    save_path = os.path.join(save_dir, "ssim_bar_chart.png")
    plt.savefig(save_path, dpi=200, bbox_inches='tight')
    plt.close()
    print(f"✅ Saved SSIM Bar Chart → {save_path}")


def plot_psnr_ssim_combined(df, save_dir):
    fig, ax1 = plt.subplots(figsize=(14, 6))

    methods = df["Method"]
    psnr = df["PSNR (dB)"].astype(float)
    ssim = df["SSIM"].astype(float)

    ax1.set_xlabel("Method")
    ax1.set_ylabel("PSNR (dB)", color="tab:blue")
    ax1.plot(methods, psnr, marker="o", color="tab:blue", linewidth=3)
    ax1.tick_params(axis='x', rotation=45)
    ax1.tick_params(axis='y', labelcolor="tab:blue")

    ax2 = ax1.twinx()
    ax2.set_ylabel("SSIM", color="tab:green")
    ax2.plot(methods, ssim, marker="o", color="tab:green", linewidth=3)
    ax2.set_ylim([0, 1])
    ax2.tick_params(axis='y', labelcolor="tab:green")

    plt.title("PSNR & SSIM Combined Graph", fontsize=16, fontweight='bold')
    plt.tight_layout()

    save_path = os.path.join(save_dir, "psnr_ssim_combined.png")
    plt.savefig(save_path, dpi=200, bbox_inches='tight')
    plt.close()
    print(f"✅ Saved PSNR+SSIM Combined Graph → {save_path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", type=str, required=True,
                        help="Path to comparison_table.csv generated by your pipeline.")
    parser.add_argument("--save_dir", type=str, default="results/graphs",
                        help="Directory to save graphs")
    
    args = parser.parse_args()

    os.makedirs(args.save_dir, exist_ok=True)

    print(f"\n📄 Loading CSV → {args.csv}")
    df = pd.read_csv(args.csv)

    plot_psnr(df, args.save_dir)
    plot_ssim(df, args.save_dir)
    plot_psnr_bar(df, args.save_dir)
    plot_ssim_bar(df, args.save_dir)
    plot_psnr_ssim_combined(df, args.save_dir)

    print("\n🎉 All graphs generated successfully!")

if __name__ == "__main__":
    main()
